from colorama import Fore

def man_normal():
    print(Fore.BLUE)
    print(" ████████████ ".center(115))
    print(" ██        ██ ".center(115))
    print(" █  █    █  █ ".center(115))
    print(" █          █ ".center(115))
    print("  █  ████  █  ".center(115))
    print("   █      █   ".center(115))
    print("   ████████   ".center(115))
    print("   █  ██  █   ".center(115))
    print("  █   ██   █  ".center(115))
    print(" █    ██    █ ".center(115))
    print("█     ██     █".center(115))
    print("█            █".center(115))
    print("█            █".center(115))
    print("█            █".center(115))
    print("_______████████████████████████████████████████████_______".center(115))
    print(Fore.RESET)

#Graficos para la mujer
def agatha_art():
    print(Fore.GREEN)
    print("██████████████".center(115))
    print("███        ███".center(115))
    print("██  █    █  ██".center(115))
    print("██          ██".center(115))
    print("██    ██    ██".center(115))
    print("████      ████".center(115))
    print("  ███    ███  ".center(115))
    print("   █      █   ".center(115))
    print("  █        █  ".center(115))
    print(" █          █ ".center(115))
    print("█            █".center(115))
    print("█            █".center(115))
    print("█            █".center(115))
    print("█            █".center(115))
    print("_______████████████████████████████████████████████_______".center(115))
    print(Fore.RESET)

def beatrice_art():
    print(Fore.MAGENTA)
    print("██████████████".center(115))
    print("███        ███".center(115))
    print("██  █    █  ██".center(115))
    print("██          ██".center(115))
    print("██    ██    ██".center(115))
    print("████      ████".center(115))
    print("  ███    ███  ".center(115))
    print("   █      █   ".center(115))
    print("  █        █  ".center(115))
    print(" █          █ ".center(115))
    print("█            █".center(115))
    print("█            █".center(115))
    print("█            █".center(115))
    print("█            █".center(115))
    print("_______████████████████████████████████████████████_______".center(115))
    print(Fore.RESET)

def victoria_art():
    print(Fore.YELLOW)
    print("██████████████".center(115))
    print("███        ███".center(115))
    print("██  █    █  ██".center(115))
    print("██          ██".center(115))
    print("██    ██    ██".center(115))
    print("████      ████".center(115))
    print("  ███    ███  ".center(115))
    print("   █      █   ".center(115))
    print("  █        █  ".center(115))
    print(" █          █ ".center(115))
    print("█            █".center(115))
    print("█            █".center(115))
    print("█            █".center(115))
    print("█            █".center(115))
    print("_______████████████████████████████████████████████_______".center(115))
    print(Fore.RESET)